import type { RouteDefinition } from '../router'
import { Router } from '../router'
import type { NorteOptions, NorteStore, OpenAPIRouteMetadata } from '../types'

export class OpenAPIGenerator {
  #metadata: OpenAPIRouteMetadata[] = []
  #cachedDocument: Record<string, unknown> | null = null
  #openapiOptions: NorteOptions['openapi']

  constructor(openapiOptions?: NorteOptions['openapi']) {
    this.#openapiOptions = openapiOptions
  }

  public addRouteMetadata<TStore extends NorteStore>(
    definition: RouteDefinition<TStore>,
    fullPath: string,
  ): void {
    const metadata = this.#extractMetadata(definition, fullPath)
    this.#metadata.push(metadata)
    this.#cachedDocument = null
  }

  public generateDocument(): Record<string, unknown> {
    if (this.#cachedDocument) {
      return this.#cachedDocument
    }

    const paths: Record<string, Record<string, unknown>> = {}

    for (const route of this.#metadata) {
      if (!paths[route.path]) {
        paths[route.path] = {}
      }

      const pathItem = paths[route.path]
      if (!pathItem) {
        continue
      }

      const operation: Record<string, unknown> = {
        operationId: route.operationId,
        summary: route.summary,
        tags: route.tags,
        responses: route.responses,
        'x-norte-invalidates': route['x-norte-invalidates'],
        'x-norte-domain': route['x-norte-domain'],
        'x-norte-version': route['x-norte-version'],
      }

      if (route.requestBody) {
        operation.requestBody = route.requestBody
      }

      if (route.parameters) {
        operation.parameters = route.parameters
      }

      pathItem[route.method] = operation
    }

    this.#cachedDocument = {
      openapi: '3.0.3',
      info: {
        title: this.#openapiOptions?.title ?? 'Norte API',
        version: this.#openapiOptions?.version ?? '1.0.0',
        description:
          this.#openapiOptions?.description ??
          'API generated by Norte Framework',
      },
      servers: this.#openapiOptions?.servers ?? [
        {
          url: 'http://localhost:3000',
          description: 'Development server',
        },
      ],
      paths,
      components: {
        schemas: {},
        securitySchemes: {},
      },
    }

    return this.#cachedDocument
  }

  #extractMetadata<TStore extends NorteStore>(
    definition: RouteDefinition<TStore>,
    fullPath: string,
  ): OpenAPIRouteMetadata {
    const { method, options, router } = definition
    const routerInternals = Router.getInternals(router)
    const { domain, options: routerOptions } = routerInternals
    const version = routerOptions.version ?? 1

    const openApiPath = fullPath.replace(/:(\w+)/g, '{$1}')

    const operationId = this.#generateOperationId(method, fullPath, domain)

    let requestBody: Record<string, unknown> | undefined
    if (options.body) {
      requestBody = {
        required: true,
        content: {
          'application/json': {
            schema: options.body,
          },
        },
      }
    }

    const parameters: Array<Record<string, unknown>> = []

    if (options.query) {
      const queryProps = (options.query as any).properties || {}
      for (const [name, schema] of Object.entries(queryProps)) {
        parameters.push({
          name,
          in: 'query',
          required: (options.query as any).required?.includes(name) ?? false,
          schema,
        })
      }
    }

    if (options.param) {
      const paramProps = (options.param as any).properties || {}
      for (const [name, schema] of Object.entries(paramProps)) {
        parameters.push({
          name,
          in: 'path',
          required: true,
          schema,
        })
      }
    }

    const defaultStatus = this.#getDefaultStatus(method)

    const responses: Record<string, Record<string, unknown>> = {}

    if (defaultStatus === 204) {
      responses['204'] = {
        description: 'No content',
      }
    } else {
      const isListMethod =
        method.toUpperCase() === 'GET' && definition.path === ''
      responses[String(defaultStatus)] = {
        description: 'Successful response',
        content: {
          'application/json': {
            schema: isListMethod
              ? {
                  type: 'array',
                  items: routerOptions.schema,
                }
              : routerOptions.schema,
          },
        },
      }
    }

    responses['400'] = { description: 'Invalid input' }
    responses['500'] = { description: 'Internal server error' }

    const invalidates = this.#calculateInvalidationHints(
      method,
      domain,
      fullPath,
    )

    const metadata: OpenAPIRouteMetadata = {
      method: method.toLowerCase(),
      path: openApiPath,
      summary: this.#generateSummary(method, domain),
      tags: [domain],
      operationId,
      responses,
      'x-norte-domain': domain,
      'x-norte-version': version,
    }

    if (requestBody) {
      metadata.requestBody = requestBody
    }

    if (parameters.length > 0) {
      metadata.parameters = parameters
    }

    if (invalidates) {
      metadata['x-norte-invalidates'] = invalidates
    }

    return metadata
  }

  #generateOperationId(method: string, path: string, domain: string): string {
    const domainId = domain.endsWith('s')
      ? `${domain.slice(0, -1)}Id`
      : `${domain}Id`
    const isReadOperation = path.endsWith(`:${domainId}`)

    const methodMap: Record<string, string> = {
      GET: isReadOperation ? 'read' : 'list',
      POST: 'create',
      PATCH: 'update',
      DELETE: 'delete',
    }

    const prefix = methodMap[method.toUpperCase()] || method.toLowerCase()
    const domainSingular = domain.endsWith('s') ? domain.slice(0, -1) : domain

    return `${prefix}${domainSingular.charAt(0).toUpperCase()}${domainSingular.slice(1)}`
  }

  #generateSummary(method: string, domain: string): string {
    const methodMap: Record<string, string> = {
      GET: 'List',
      POST: 'Create',
      PATCH: 'Update',
      DELETE: 'Delete',
    }

    const action = methodMap[method.toUpperCase()] || method
    return `${action} ${domain}`
  }

  #calculateInvalidationHints(
    method: string,
    domain: string,
    fullPath: string,
  ): string[] | undefined {
    const upperMethod = method.toUpperCase()

    if (['POST', 'PATCH', 'DELETE'].includes(upperMethod)) {
      const hints: string[] = []

      const listPath = fullPath.split('/:')[0]
      hints.push(`${upperMethod === 'POST' ? 'GET' : upperMethod} ${listPath}`)

      const pathParts = fullPath.split('/')
      for (let i = pathParts.length - 1; i >= 0; i--) {
        if (pathParts[i]?.startsWith(':')) {
          const parentPath = pathParts.slice(0, i).join('/')
          if (parentPath.includes(domain)) {
            hints.push(`GET ${parentPath}`)
          }
        }
      }

      return hints.length > 0 ? hints : undefined
    }

    return undefined
  }

  #getDefaultStatus(method: string): number {
    switch (method.toUpperCase()) {
      case 'POST':
        return 201
      case 'DELETE':
        return 204
      default:
        return 200
    }
  }
}
