import type { ParsedOpenAPI, ParsedOperation } from './openapi-parser'

interface JSONSchema {
  type?: string
  properties?: Record<string, unknown>
  required?: string[]
  items?: unknown
  [key: string]: unknown
}

export function generateFetchClient(
  openapi: ParsedOpenAPI,
): Record<string, string> {
  const files: Record<string, string> = {}

  // Group operations by domain
  const domains = new Map<string, ParsedOperation[]>()

  for (const op of openapi.operations) {
    const domain = op.domain || 'api'
    if (!domains.has(domain)) {
      domains.set(domain, [])
    }
    domains.get(domain)?.push(op)
  }

  // Generate a file for each domain
  for (const [domain, operations] of domains.entries()) {
    const content = generateDomainClient(domain, operations, openapi)
    files[`${domain}.ts`] = content
  }

  // Generate index file
  files['index.ts'] = generateIndexFile(Array.from(domains.keys()))

  // Generate types file
  files['types.ts'] = generateTypesFile()

  return files
}

function generateDomainClient(
  _domain: string,
  operations: ParsedOperation[],
  openapi: ParsedOpenAPI,
): string {
  const baseUrl = openapi.servers?.[0]?.url || ''

  let content = '// Generated by Norte CLI - Do not edit manually\n'
  content += `import type { ApiError, RequestOptions } from './types'\n\n`

  // Generate types for this domain
  const types = generateDomainTypes(operations)
  if (types) {
    content += `${types}\n\n`
  }

  // Generate functions for each operation
  for (const op of operations) {
    content += generateOperationFunction(op, baseUrl)
    content += '\n\n'
  }

  return content.trim()
}

function generateDomainTypes(operations: ParsedOperation[]): string {
  let types = ''

  for (const op of operations) {
    // Generate request type if there's a body
    if (op.requestBody) {
      const typeName = `${capitalize(op.id)}Input`
      types += `export type ${typeName} = ${schemaToType(op.requestBody)}\n\n`
    }

    // Generate response type
    if (op.responseSchema) {
      const typeName = `${capitalize(op.id)}Response`
      types += `export type ${typeName} = ${schemaToType(op.responseSchema)}\n\n`
    }
  }

  return types.trim()
}

function generateOperationFunction(
  op: ParsedOperation,
  baseUrl: string,
): string {
  const funcName = op.id
  const hasBody = op.requestBody !== undefined
  const pathParams = op.parameters.filter((p) => p.in === 'path')
  const queryParams = op.parameters.filter((p) => p.in === 'query')

  // Build parameter list
  const params: string[] = []

  if (pathParams.length > 0) {
    const pathParamType = pathParams.map((p) => `${p.name}: string`).join(', ')
    params.push(pathParamType)
  }

  if (hasBody) {
    params.push(`body: ${capitalize(op.id)}Input`)
  }

  if (queryParams.length > 0) {
    const queryParamType = `query?: { ${queryParams.map((p) => `${p.name}?: ${getTypeFromSchema(p.schema)}`).join(', ')} }`
    params.push(queryParamType)
  }

  params.push('options?: RequestOptions')

  // Build return type
  const returnType = op.responseSchema
    ? `Promise<${capitalize(op.id)}Response>`
    : 'Promise<void>'

  // Build path with parameters
  let urlPath = op.path
  for (const param of pathParams) {
    urlPath = urlPath.replace(`{${param.name}}`, `\${${param.name}}`)
  }

  let func = `export async function ${funcName}(${params.join(', ')}): ${returnType} {\n`
  func += `  const url = \`${baseUrl}${urlPath}\``

  if (queryParams.length > 0) {
    func += ` + (query ? '?' + new URLSearchParams(query as Record<string, string>).toString() : '')`
  }

  func += '\n\n'
  func += '  const response = await fetch(url, {\n'
  func += `    method: '${op.method}',\n`
  func += '    headers: {\n'
  func += `      'Content-Type': 'application/json',\n`
  func += '      ...options?.headers,\n'
  func += '    },\n'

  if (hasBody) {
    func += '    body: JSON.stringify(body),\n'
  }

  func += '  })\n\n'
  func += '  if (!response.ok) {\n'
  func += '    const error: ApiError = await response.json().catch(() => ({\n'
  func += `      error: 'UNKNOWN_ERROR',\n`
  func += '      message: response.statusText,\n'
  func += '    }))\n'
  func += '    throw error\n'
  func += '  }\n\n'

  if (op.responseSchema) {
    func += '  return await response.json()\n'
  }

  func += '}'

  return func
}

function generateIndexFile(domains: string[]): string {
  let content = '// Generated by Norte CLI - Do not edit manually\n'

  for (const domain of domains) {
    content += `export * from './${domain}'\n`
  }

  content += `export * from './types'\n`

  return content
}

function generateTypesFile(): string {
  return `// Generated by Norte CLI - Do not edit manually

export type ApiError = {
  error: string
  message: string
}

export type RequestOptions = {
  headers?: Record<string, string>
}
`
}

function schemaToType(schema: unknown): string {
  if (!schema || typeof schema !== 'object') {
    return 'unknown'
  }

  const s = schema as JSONSchema

  if (s.type === 'array') {
    return `Array<${schemaToType(s.items)}>`
  }

  if (s.type === 'object' && s.properties) {
    const props = Object.entries(s.properties)
      .map(([key, value]) => {
        const required = s.required?.includes(key) ?? false
        const optional = required ? '' : '?'
        return `${key}${optional}: ${schemaToType(value)}`
      })
      .join('; ')
    return `{ ${props} }`
  }

  // Primitive types
  switch (s.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    default:
      return 'unknown'
  }
}

function getTypeFromSchema(schema: unknown): string {
  if (!schema || typeof schema !== 'object') {
    return 'string'
  }

  const s = schema as JSONSchema

  switch (s.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    default:
      return 'string'
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
