import type { ParsedOpenAPI, ParsedOperation } from './openapi-parser'

export function generateTanStackQuery(
  openapi: ParsedOpenAPI,
): Record<string, string> {
  const files: Record<string, string> = {}

  // Group operations by domain
  const domains = new Map<string, ParsedOperation[]>()

  for (const op of openapi.operations) {
    const domain = op.domain || 'api'
    if (!domains.has(domain)) {
      domains.set(domain, [])
    }
    domains.get(domain)?.push(op)
  }

  // Generate base client first (fetch functions)
  for (const [domain, operations] of domains.entries()) {
    const clientContent = generateDomainFetchFunctions(
      domain,
      operations,
      openapi,
    )
    files[`${domain}.client.ts`] = clientContent

    // Generate hooks file
    const hooksContent = generateDomainHooks(domain, operations)
    files[`${domain}.hooks.ts`] = hooksContent
  }

  // Generate index file
  files['index.ts'] = generateTanStackIndexFile(Array.from(domains.keys()))

  // Generate types file
  files['types.ts'] = generateTanStackTypesFile()

  return files
}

function generateDomainFetchFunctions(
  _domain: string,
  operations: ParsedOperation[],
  openapi: ParsedOpenAPI,
): string {
  const baseUrl = openapi.servers?.[0]?.url || ''

  let content = '// Generated by Norte CLI - Do not edit manually\n'
  content += `import type { ApiError, RequestOptions } from './types'\n\n`

  // Generate types for this domain
  const types = generateDomainTypes(operations)
  if (types) {
    content += `${types}\n\n`
  }

  // Generate functions for each operation
  for (const op of operations) {
    content += generateFetchFunction(op, baseUrl)
    content += '\n\n'
  }

  return content.trim()
}

function generateDomainHooks(
  domain: string,
  operations: ParsedOperation[],
): string {
  let content = '// Generated by Norte CLI - Do not edit manually\n'
  content += `import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'\n`
  content += `import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query'\n`
  content += `import * as client from './${domain}.client'\n\n`

  // Generate query keys factory
  content += generateQueryKeysFactory(domain, operations)
  content += '\n\n'

  // Generate hooks for each operation
  for (const op of operations) {
    if (op.method === 'GET') {
      content += generateQueryHook(op, domain)
    } else {
      content += generateMutationHook(op, domain, operations)
    }
    content += '\n\n'
  }

  return content.trim()
}

function generateQueryKeysFactory(
  domain: string,
  operations: ParsedOperation[],
): string {
  const singularDomain = domain.endsWith('s') ? domain.slice(0, -1) : domain

  let keys = `export const ${singularDomain}Keys = {\n`
  keys += `  all: ['${domain}'] as const,\n`
  keys += `  lists: () => [...${singularDomain}Keys.all, 'list'] as const,\n`
  keys += `  list: (filters?: Record<string, unknown>) => [...${singularDomain}Keys.lists(), filters] as const,\n`
  keys += `  details: () => [...${singularDomain}Keys.all, 'detail'] as const,\n`
  keys += `  detail: (id: string) => [...${singularDomain}Keys.details(), id] as const,\n`

  // Add custom keys for other GET operations
  const customGets = operations.filter(
    (op) =>
      op.method === 'GET' &&
      !op.id.startsWith('list') &&
      !op.id.startsWith('read'),
  )

  for (const op of customGets) {
    const keyName = op.id.replace(/^get/, '').replace(/^read/, '')
    keys += `  ${keyName}: (params?: Record<string, unknown>) => [...${singularDomain}Keys.all, '${keyName}', params] as const,\n`
  }

  keys += '}'

  return keys
}

function generateQueryHook(op: ParsedOperation, domain: string): string {
  const hookName = `use${capitalize(op.id)}`
  const singularDomain = domain.endsWith('s') ? domain.slice(0, -1) : domain
  const pathParams = op.parameters.filter((p) => p.in === 'path')
  const queryParams = op.parameters.filter((p) => p.in === 'query')

  // Build parameter list
  const params: string[] = []

  if (pathParams.length > 0) {
    params.push(pathParams.map((p) => `${p.name}: string`).join(', '))
  }

  if (queryParams.length > 0) {
    const queryType = `query?: { ${queryParams.map((p) => `${p.name}?: ${getTypeFromSchema(p.schema)}`).join(', ')} }`
    params.push(queryType)
  }

  // Determine query key
  let queryKey: string
  if (op.id.startsWith('list')) {
    queryKey = `${singularDomain}Keys.list(query)`
  } else if (op.id.startsWith('read')) {
    const idParam = pathParams.find((p) => p.name.endsWith('Id'))
    queryKey = idParam
      ? `${singularDomain}Keys.detail(${idParam.name})`
      : `${singularDomain}Keys.details()`
  } else {
    const keyName = op.id.replace(/^get/, '').replace(/^read/, '')
    queryKey = `${singularDomain}Keys.${keyName}({ ${pathParams.map((p) => p.name).join(', ')}, ...query })`
  }

  const returnType = op.responseSchema ? `${capitalize(op.id)}Response` : 'void'
  const optionsType = `UseQueryOptions<${returnType}, ApiError>`

  params.push(`options?: Omit<${optionsType}, 'queryKey' | 'queryFn'>`)

  // Generate hook
  let hook = `export function ${hookName}(${params.join(', ')}) {\n`
  hook += `  return useQuery<${returnType}, ApiError>({\n`
  hook += `    queryKey: ${queryKey},\n`
  hook += `    queryFn: () => client.${op.id}(${[...pathParams.map((p) => p.name), queryParams.length > 0 ? 'query' : ''].filter(Boolean).join(', ')}),\n`
  hook += '    ...options,\n'
  hook += '  })\n'
  hook += '}'

  return hook
}

function generateMutationHook(
  op: ParsedOperation,
  domain: string,
  allOperations: ParsedOperation[],
): string {
  const hookName = `use${capitalize(op.id)}`
  const singularDomain = domain.endsWith('s') ? domain.slice(0, -1) : domain
  const hasBody = op.requestBody !== undefined
  const pathParams = op.parameters.filter((p) => p.in === 'path')

  // Build input type
  let inputType = 'void'
  if (hasBody && pathParams.length > 0) {
    inputType = `{ ${pathParams.map((p) => `${p.name}: string`).join(', ')}, body: ${capitalize(op.id)}Input }`
  } else if (hasBody) {
    inputType = `${capitalize(op.id)}Input`
  } else if (pathParams.length > 0) {
    inputType = `{ ${pathParams.map((p) => `${p.name}: string`).join(', ')} }`
  }

  const returnType = op.responseSchema ? `${capitalize(op.id)}Response` : 'void'
  const optionsType = `UseMutationOptions<${returnType}, ApiError, ${inputType}>`

  // Parse invalidation hints
  const invalidations = parseInvalidationHints(
    op.invalidates,
    singularDomain,
    allOperations,
  )

  let hook = `export function ${hookName}(options?: Omit<${optionsType}, 'mutationFn'>) {\n`
  hook += '  const queryClient = useQueryClient()\n\n'
  hook += `  return useMutation<${returnType}, ApiError, ${inputType}>({\n`

  // Build mutation function
  if (hasBody && pathParams.length > 0) {
    hook += `    mutationFn: (input) => client.${op.id}(${pathParams.map((p) => `input.${p.name}`).join(', ')}, input.body),\n`
  } else if (hasBody) {
    hook += `    mutationFn: (body) => client.${op.id}(body),\n`
  } else if (pathParams.length > 0) {
    hook += `    mutationFn: (input) => client.${op.id}(${pathParams.map((p) => `input.${p.name}`).join(', ')}),\n`
  } else {
    hook += `    mutationFn: () => client.${op.id}(),\n`
  }

  // Add onSuccess with invalidations
  if (invalidations.length > 0) {
    hook += '    onSuccess: (data, variables, context) => {\n'
    hook += '      // Auto-invalidate based on x-norte-invalidates hints\n'
    for (const inv of invalidations) {
      hook += `      queryClient.invalidateQueries({ queryKey: ${inv} })\n`
    }
    hook += '      options?.onSuccess?.(data, variables, context)\n'
    hook += '    },\n'
  }

  hook += '    ...options,\n'
  hook += '  })\n'
  hook += '}'

  return hook
}

function parseInvalidationHints(
  hints: string[],
  domain: string,
  allOperations: ParsedOperation[],
): string[] {
  const invalidations: string[] = []

  for (const hint of hints) {
    // hint format: "GET /v1/users" or "POST /v1/stores/:storeId/products"
    const [method, path] = hint.split(' ')

    // Find matching operation
    const matchingOp = allOperations.find(
      (op) => op.method === method && op.path === path,
    )

    if (matchingOp) {
      if (matchingOp.id.startsWith('list')) {
        invalidations.push(`${domain}Keys.lists()`)
      } else if (matchingOp.id.startsWith('read')) {
        invalidations.push(`${domain}Keys.details()`)
      }
    } else {
      // Generic invalidation - invalidate all lists
      invalidations.push(`${domain}Keys.lists()`)
    }
  }

  // Remove duplicates
  return Array.from(new Set(invalidations))
}

function generateTanStackIndexFile(domains: string[]): string {
  let content = '// Generated by Norte CLI - Do not edit manually\n'

  for (const domain of domains) {
    content += `export * from './${domain}.client'\n`
    content += `export * from './${domain}.hooks'\n`
  }

  content += `export * from './types'\n`

  return content
}

function generateTanStackTypesFile(): string {
  return `// Generated by Norte CLI - Do not edit manually

export type ApiError = {
  error: string
  message: string
}

export type RequestOptions = {
  headers?: Record<string, string>
}
`
}

// Helper functions (reused from client-base)

function generateDomainTypes(operations: ParsedOperation[]): string {
  let types = ''

  for (const op of operations) {
    if (op.requestBody) {
      const typeName = `${capitalize(op.id)}Input`
      types += `export type ${typeName} = ${schemaToType(op.requestBody)}\n\n`
    }

    if (op.responseSchema) {
      const typeName = `${capitalize(op.id)}Response`
      types += `export type ${typeName} = ${schemaToType(op.responseSchema)}\n\n`
    }
  }

  return types.trim()
}

function generateFetchFunction(op: ParsedOperation, baseUrl: string): string {
  const funcName = op.id
  const hasBody = op.requestBody !== undefined
  const pathParams = op.parameters.filter((p) => p.in === 'path')
  const queryParams = op.parameters.filter((p) => p.in === 'query')

  const params: string[] = []

  if (pathParams.length > 0) {
    const pathParamType = pathParams.map((p) => `${p.name}: string`).join(', ')
    params.push(pathParamType)
  }

  if (hasBody) {
    params.push(`body: ${capitalize(op.id)}Input`)
  }

  if (queryParams.length > 0) {
    const queryParamType = `query?: { ${queryParams.map((p) => `${p.name}?: ${getTypeFromSchema(p.schema)}`).join(', ')} }`
    params.push(queryParamType)
  }

  params.push('options?: RequestOptions')

  const returnType = op.responseSchema
    ? `Promise<${capitalize(op.id)}Response>`
    : 'Promise<void>'

  let urlPath = op.path
  for (const param of pathParams) {
    urlPath = urlPath.replace(`{${param.name}}`, `\${${param.name}}`)
  }

  let func = `export async function ${funcName}(${params.join(', ')}): ${returnType} {\n`
  func += `  const url = \`${baseUrl}${urlPath}\``

  if (queryParams.length > 0) {
    func += ` + (query ? '?' + new URLSearchParams(query as any).toString() : '')`
  }

  func += '\n\n'
  func += '  const response = await fetch(url, {\n'
  func += `    method: '${op.method}',\n`
  func += '    headers: {\n'
  func += `      'Content-Type': 'application/json',\n`
  func += '      ...options?.headers,\n'
  func += '    },\n'

  if (hasBody) {
    func += '    body: JSON.stringify(body),\n'
  }

  func += '  })\n\n'
  func += '  if (!response.ok) {\n'
  func += '    const error: ApiError = await response.json().catch(() => ({\n'
  func += `      error: 'UNKNOWN_ERROR',\n`
  func += '      message: response.statusText,\n'
  func += '    }))\n'
  func += '    throw error\n'
  func += '  }\n\n'

  if (op.responseSchema) {
    func += '  return await response.json()\n'
  }

  func += '}'

  return func
}

function schemaToType(schema: unknown): string {
  if (!schema || typeof schema !== 'object') {
    return 'unknown'
  }

  const s = schema as any

  if (s.type === 'array') {
    return `Array<${schemaToType(s.items)}>`
  }

  if (s.type === 'object' && s.properties) {
    const props = Object.entries(s.properties)
      .map(([key, value]) => {
        const required = s.required?.includes(key) ?? false
        const optional = required ? '' : '?'
        return `${key}${optional}: ${schemaToType(value)}`
      })
      .join('; ')
    return `{ ${props} }`
  }

  switch (s.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    default:
      return 'unknown'
  }
}

function getTypeFromSchema(schema: unknown): string {
  if (!schema || typeof schema !== 'object') {
    return 'string'
  }

  const s = schema as any

  switch (s.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    default:
      return 'string'
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
